INSERT INTO [CATEGORIES] ([ID], [NAME])	
VALUES 
     (NEWID(), 'INFORMATICA'),
     (NEWID(), 'ELETRODOMESTICAS'),
     (NEWID(), 'LIVRARIA'),
     (NEWID(), 'GAMES'),
     (NEWID(), 'VESTUARIO'),
     (NEWID(), 'MATERIAIS DE ESCRITORIO'),
     (NEWID(), 'CAMA, MESA E BANHO'),
     (NEWID(), 'OUTROS');

     SELECT * FROM CATEGORIES
     ORDER BY NAME ASC;